name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create SSH key file
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 65.0.86.176
          username: ubuntu
          key_path: /github/home/.ssh/id_rsa
          script: |
            echo "Connected successfully"
