name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Write SSH key to file
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 65.0.86.176
          username: ubuntu
          key_path: private_key.pem
          script: |
            echo "Connected successfully"
